### ISSUE TITLE
请问下LUCI如何修改？

### ISSUE THREAD

**Issue by 518512** [roacn/OpenWrt#6]
lede|Lede|LEDE)
		SOURCE_URL="https://github.com/coolsnowwolf/lede"
		SOURCE="lede"
		SOURCE_OWNER="Lean's"
		LUCI_EDITION="18.06"

好像只有18.06可以生效，改成其他比如：24.10， 和18.06一样，编译出来还是 LuCI openwrt-23.05

**Comment by roacn** [comment]
已经增加了luci版本选择，可以在settings.ini文件里设置，或者编译界面手动选择。
lede源码目前有18.06与23.05两个版本可以选择。

settings.ini文件中的插件，PACKAGES_BRANCH="Official"对应23.05版本，PACKAGES_BRANCH="Lede"对应旧的18.06版本。

重新拉一下源码，设置下就可以。
